### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by dangershony** [NLightning/NLightning#22]
If not what are the reasons?

**Comment by dmsch** [comment]
This project is unmaintained, but DotNetLightning is maintained:
https://github.com/joemphilips/DotNetLightning

**Comment by dangershony** [comment]
Awesome thanks

**Comment by knocte** [comment]
@dangershony AFAIU you're a C# dev; in case the F# used in DNL puts you off, I wrote this guide that you might (hopefullly) like: https://github.com/knocte/2fsharp/blob/master/csharp2fsharp.md

**Comment by dangershony** [comment]
Brilliant thank you mate this does help 👍
